# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c63dd61d72669b036b2a9ee84427d2276eec317caf7fbb29275885c260a019a35d314d7b099fdecdf82b123904105b30a2998ff51fb9ef907b5390e0efb6c49

test:
  secret_key_base: a8928a211aade8e423f0b8fecc814faa593d8e9fc366e9a19265ab77c44420668420726017282fe4946cfe1042bcf7845934591fa3a39cfb6f3602cf8167fc4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
